# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31500
    hostPort: 31500
    protocol: TCP
  - containerPort: 32500
    hostPort: 32500
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 31501
    hostPort: 31501
    protocol: TCP
  - containerPort: 32501
    hostPort: 32501
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 31502
    hostPort: 31502
    protocol: TCP
  - containerPort: 32502
    hostPort: 32502
    protocol: TCP
